"""Sample transaction data for the demo API."""

from __future__ import annotations

from datetime import datetime, timezone

from app.models import Transaction

SAMPLE_TRANSACTIONS: list[Transaction] = [
    Transaction(
        id=1,
        amount=250.00,
        currency="USD",
        description="Wire transfer to vendor",
        timestamp=datetime(2025, 1, 15, 10, 30, 0, tzinfo=timezone.utc),
        category="transfer",
    ),
    Transaction(
        id=2,
        amount=-45.99,
        currency="USD",
        description="Office supplies purchase",
        timestamp=datetime(2025, 1, 16, 14, 22, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=3,
        amount=1200.00,
        currency="USD",
        description="Client payment received",
        timestamp=datetime(2025, 1, 17, 9, 0, 0, tzinfo=timezone.utc),
        category="income",
    ),
    Transaction(
        id=4,
        amount=-89.50,
        currency="USD",
        description="Software subscription",
        timestamp=datetime(2025, 1, 18, 11, 45, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=5,
        amount=-320.00,
        currency="USD",
        description="Equipment lease payment",
        timestamp=datetime(2025, 1, 19, 8, 15, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=6,
        amount=5000.00,
        currency="USD",
        description="Quarterly revenue deposit",
        timestamp=datetime(2025, 1, 20, 16, 0, 0, tzinfo=timezone.utc),
        category="income",
    ),
    Transaction(
        id=7,
        amount=-150.75,
        currency="USD",
        description="Team lunch expense",
        timestamp=datetime(2025, 1, 21, 12, 30, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=8,
        amount=750.00,
        currency="USD",
        description="Consulting fee received",
        timestamp=datetime(2025, 1, 22, 10, 0, 0, tzinfo=timezone.utc),
        category="income",
    ),
    Transaction(
        id=9,
        amount=-29.99,
        currency="USD",
        description="Cloud hosting bill",
        timestamp=datetime(2025, 1, 23, 7, 0, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=10,
        amount=-500.00,
        currency="USD",
        description="Insurance premium",
        timestamp=datetime(2025, 1, 24, 9, 30, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=11,
        amount=3200.00,
        currency="USD",
        description="Project milestone payment",
        timestamp=datetime(2025, 1, 25, 14, 0, 0, tzinfo=timezone.utc),
        category="income",
    ),
    Transaction(
        id=12,
        amount=-75.00,
        currency="USD",
        description="Parking fees",
        timestamp=datetime(2025, 1, 26, 8, 0, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=13,
        amount=180.00,
        currency="USD",
        description="Refund from supplier",
        timestamp=datetime(2025, 1, 27, 11, 15, 0, tzinfo=timezone.utc),
        category="refund",
    ),
    Transaction(
        id=14,
        amount=-1100.00,
        currency="USD",
        description="Contractor payment",
        timestamp=datetime(2025, 1, 28, 15, 45, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=15,
        amount=420.00,
        currency="USD",
        description="Interest earned",
        timestamp=datetime(2025, 1, 29, 10, 0, 0, tzinfo=timezone.utc),
        category="income",
    ),
    Transaction(
        id=16,
        amount=-60.00,
        currency="USD",
        description="Domain renewal",
        timestamp=datetime(2025, 1, 30, 9, 0, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=17,
        amount=950.00,
        currency="USD",
        description="Ad revenue payout",
        timestamp=datetime(2025, 1, 31, 13, 30, 0, tzinfo=timezone.utc),
        category="income",
    ),
    Transaction(
        id=18,
        amount=-200.00,
        currency="USD",
        description="Travel expense reimbursement",
        timestamp=datetime(2025, 2, 1, 10, 0, 0, tzinfo=timezone.utc),
        category="expense",
    ),
    Transaction(
        id=19,
        amount=2800.00,
        currency="USD",
        description="Annual subscription payment",
        timestamp=datetime(2025, 2, 2, 8, 0, 0, tzinfo=timezone.utc),
        category="income",
    ),
    Transaction(
        id=20,
        amount=-35.00,
        currency="USD",
        description="Postage and shipping",
        timestamp=datetime(2025, 2, 3, 14, 0, 0, tzinfo=timezone.utc),
        category="expense",
    ),
]
